import java_cup.runtime.*; 
	scan with {: return getScanner().next_token(); :};
	terminal INT,STRING,SEMI,COMMA,ID, SPACE, EOFILE;
	non terminal prog, stmt,progstmt, decln, varlist, type, s;
	s ::= prog {: System.out.println("Valid declaration"); :}	
EOFILE {:System.exit(0);:} ;
	prog ::= progstmt |stmt ;
	stmt ::= decln;
	decln ::= type SPACE varlist SEMI;
	type ::= INT | STRING ;
	varlist ::= ID COMMA varlist | ID ;