
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 08 14:44:51 IST 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 2;
  public static final int oparan = 12;
  public static final int EOFILE = 8;
  public static final int ccparan = 15;
  public static final int SEMI = 4;
  public static final int EQ = 9;
  public static final int EOF = 0;
  public static final int STRING = 3;
  public static final int cparan = 13;
  public static final int ID = 6;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int SPACE = 7;
  public static final int coparan = 14;
  public static final int CONST = 11;
  public static final int FLOAT = 10;
}

